### ISSUE TITLE
Fix 14 pre-existing test failures exposed by test data regeneration

### ISSUE THREAD

**Issue by lair-click-bats** [lair-click-bats/tracekit#11]
## Summary

After merging PR #10 which fixed corrupted test data files, 14 pre-existing test failures have been exposed. These failures **exist on the main branch** (verified by running tests on main before the PR merge) and are NOT caused by the NPZ corruption fix.

### 1. Real Waveform Capture Loading (WFM files)
- **Error**: `ZeroDivisionError: float division by zero`
- **Location**: WFM file loader
- **Impact**: Cannot load real oscilloscope captures

### 2. Edge Detection Hypothesis Tests
- **Error**: `AttributeError: 'Edge' object has no attribute 'index'`
- **Location**: Edge detection analyzer
- **Impact**: Property-based tests failing for edge detection

### 3. Entropy Hypothesis Tests
- **Error**: Various assertion errors
- **Location**: Statistical analyzers
- **Impact**: Entropy calculation tests unstable

### 4. Comparison Edge Cases
- **Error**: NaN/Inf handling failures
- **Location**: Comparison utilities
- **Impact**: Edge case handling incomplete

## Verification

These failures were verified as pre-existing by:
1. Checking out main branch (commit: 50990c9)
2. Running full test suite
3. Confirming same 14 failures exist

## Next Steps

1. Categorize failures by module
2. Fix WFM loader division by zero
3. Add missing 'index' attribute to Edge objects
4. Stabilize hypothesis property tests
5. Improve NaN/Inf edge case handling

## Context

- PR #10 successfully fixed 6 NPZ corruption failures
- These 14 failures are unrelated to NPZ corruption
- All failures are reproducible on main branch
- No regressions introduced by PR #10
